language: node_js
node_js:
- '0.10'
before_script:
- node_modules/.bin/jspm install
script: node_modules/karma/bin/karma start karma.conf.js --single-run
deploy:
  provider: npm
  email: djindjic@gmail.com
  api_key:
    secure: gKUu7ChZvTcgSnVGFagrL/3RTpZfGtIR9wnjcGidpql62FZw17bLlbJCvjvSTn8CGlpKyExfNfSiEEl8CSvIjwOMUQFGD8Z9ApdIfrErJUrHoMqwZ5DQd7LrA/2CKLr9/sGgCcAJ8opvqWrmNI0nYZxIGvrD37Of9I33fx/K+Fc=
  on:
    tags: true
    repo: djindjic/forwardablejs
